version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runsslserver 0.0.0.0:443 --certificate /etc/ssl/certs/certificate.crt --key /etc/ssl/private/private.key
    volumes:
      - ./ca_bundle.crt:/etc/ssl/certs/ca_bundle.crt
      - ./certificate.crt:/etc/ssl/certs/certificate.crt
      - ./private.key:/etc/ssl/private/private.key
    ports:
      - "8000:8000"
      - "443:443"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-web-client:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
